server:
  port: 8080
#  servlet: #设置session过期时间
#    session:x
#      timeout: 120    #单位为秒，默认为30min,设置不得少于1分钟
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.95.129:3306/mall?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: wangyi123.
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.95.129
    port: 6379
    password: Tomyredis
mybatis:
  #xml文件扫描路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
    #控制台开启sql语句输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

